# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20170720_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='married',
            field=models.BooleanField(default=False),
        ),
    ]
