# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20170720_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='married',
        ),
    ]
